kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "dbclient" 
  annotations:
    openshift.io/build-config.name: dbclient
  labels:
    build: dbclient
    buildconfig: dbclient
    openshift.io/build-config.name: dbclient
    openshift.io/build.start-policy: Serial
spec:
  source:
    contextDir: "containers/dbclient"
    git:
      ref: main
      uri: 'https://github.com/stevshil/monitoring-lab.git'
    type: Git
  strategy:
   type: Docker
   dockerStrategy:
    dockerfilePath: .
  output: 
    to:
      kind: "ImageStreamTag"
      name: "dbclient:latest"
