kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "wordpress"
  annotations:
    openshift.io/build-config.name: wordpress
  labels:
    build: wordpress
    buildconfig: wordpress
    openshift.io/build-config.name: wordpress
    openshift.io/build.start-policy: Serial
spec:
  source:
    contextDir: "containers/wordpress"
    git:
      ref: main
      uri: 'https://github.com/stevshil/monitoring-lab.git'
    type: Git
  strategy:
   type: Docker
   dockerStrategy:
    dockerfilePath: .
  output:
    to:
      kind: "ImageStreamTag"
      name: "wordpress:latest"
